- .github/workflows/ossf_scorecard.yml
- Enable Open Source Security Foundation Scorecard [Github Action](https://github.com/marketplace/actions/ossf-scorecard-action).
<details>
</details>
> ci: enable ossf scorecard action

- .github/dependabot.yml
- Updates dependabot to handle versioning for terraform modules and samples
<details>
</details>
> ci: updating dependabot.yml

- assets/packer/perforce/helix-core/README.md
- docs/getting-started.md
Updates documentation to fix packer command invocation (path provided was incorrect) and link to installation instructions for the relevant tools that need to be installed.
No changes in user experience
<details>
No
</details>
> docs: link to installation instructions for required tools, fix packer command invocation instructions

- README.md
- Adds openssf scorecard badge to our project readme
<details>
</details>
> docs: add openssf scorecard badge to readme

- assets/packer/build-agents/linux/fsx_automounter.py
This fixes an issue with the FSx automounter script where the script would terminate with an exception if there are any FSx volumes in an account that the build agents don't have the `fsx:ListTagsForResource` IAM permission for. Configurations like that are normal in cases where the Cloud Game Development Toolkit was deployed in an AWS account with existing FSx volume resources. The exception is now treated as a warning and logged so that the automounter script can continue trying to mount any other relevant volumes.
No changes in user experience
(documentation changes not needed for this fix)
<details>
No
</details>
By submitting this pull request, I …
> fix(fsx_automounter): when FSx automounter can't list tags for an FSx volume, the AccessDenied exception is now treated as a warning

- .github/workflows/changelog.yml
- update to changelog github action to rebase changes 
<details>
</details>
> ci: fix changelog github action

- .github/workflows/changelog.yml
> ci: update changelog automation

- .github/workflows/changelog.yml
Fixes Changelog automation
* [] Changes have been tested
<details>
</details>
> fix(changelog): Add automated PR creation

- .github/workflows/changelog.yml
Adjusting changelog configuration to leverage GHA bot
<details>
</details>
> fix(changelog): GHA bot committer

- .github/workflows/changelog.yml
> fix: adding branch creation to workflow

- .github/workflows/changelog.yml
> changelog automation

- .github/workflows/changelog.yml
> fix: changelog automation

- .github/workflows/changelog.yml
> updating flow for GH automated changelog creation

- .github/workflows/changelog.yml
Adjusted changelog automation to leverage GH API for signed commits.
<details>
</details>
> chore: adjusting changelog automation to leverage GH api

- .github/workflows/dependency-review.yml
> ci: update dependency review GHA

- .github/workflows/changelog.yml
**Issue number:** #182 
- Updates changelog.yaml to use PAT for `gh api`
<details>
</details>
> chore: update changelog workflow

- mkdocs.yml
- Adds documentation for a complete perforce example that deploys Helix Core, Helix Swarm and Helix Authentication Service (HAS)
<details>
</details>
> docs: add perforce complete example in docs

- modules/unreal/horde/README.md
- modules/unreal/horde/asg.tf
closes #450 
Added suggested lines from issue.
<details>
</details>
> Fixed S3 object deletion bug, and minor README update.

- docs/assets/packer/build-agents/linux.md
Updates to Ubuntu AMD & ARM links, and Linux ARM link
<details>
</details>
> Updated links

- .github/dependabot.yml
**Issue number:** n/a
Updates dependabot configuration to include unreal modules
no changes
<details>
no
</details>
> chore: update dependabot configuration to include unreal modules

- samples/simple-build-pipeline/dns.tf
**Issue number: 502**
> variable was misnamed 
> terraform apply would not work before
* [ Yes] I have performed a self-review of this change
* [Yes ] Changes have been tested
* [ Yes ] Changes are documented
<details>
</details>
> Fixed eip issue for simple build pipeline that prevented deployment

- docs/modules/unreal/horde/unreal-engine-horde.md
- docs/stylesheets/extra.css
**Issue number:** #529 
adds embedded youtube video from unreal fest to the module documentation page, includes updates to css to address iframe youtube embedding.
<details>
</details>
> docs: add unreal fest video to horde module docs

- mkdocs.yml
Adding link in documentation to Cloud DDC sample (single-region)
Add link to `mkdocs.yml`
<details>
</details>
> fix: Adding cloud DDC sample for mkdocs.yml

- docs/modules/jenkins/jenkins.md
- modules/jenkins/README.md
- modules/jenkins/alb.tf
- modules/jenkins/examples/complete/main.tf
- modules/jenkins/examples/complete/versions.tf
- modules/jenkins/variables.tf
closes #574
A debug variable was added in the Jenkins module to expedite testing. 
This variable is currently being used to force destroy ALB access log buckets.  
Helps with testing, since buckets with content are deleted.
<details>
No
</details>
> feat: Adds debug variable and flag

- modules/perforce/modules/p4-server/main.tf
**Issue number:** #648 
Previously, due to a typo, the logs and depot mappings were swapped. This would result in a 128gb logs volume and a 32gb depot volume, which is undesirable.
Use the provided variable names for volume mounts instead of hard-codes (which were incorrect).
<details>
Yes, this is a breaking change.
</details>
> fix(p4)!: correct volume attachment mapping
