aws-games/cloud-game-development-toolkit

assets/packer/perforce/helix-core/perforce.pkr.hcl

**Issue number:** #192 
Prior to installing packages, the install script now waits for cloud-init to complete
No changes to user experience
(no documentation changes necessary)
<details>
No
</details>

fix: wait for cloud-init to complete prior to installing packages during Perforce Helix Core AMI creation

---

.github/dependabot.yml

#227 
Adds dependabot grouping for terraform provider version bumps.
Add group definitions for current AWS and Random TF providers.
<details>
</details>

fix: dependabot grouping terraform providers

---

modules/unreal/horde/ecs.tf
modules/unreal/horde/variables.tf

Use the environment variable to set the ASP.NET Core runtime environment for horde server.
Admin can now see that horde server is running in the desired runtime environment when looking at the container logs.
<details>
No
</details>

Set ASP.NET Core runtime environment

---

assets/packer/build-agents/linux/amazon-linux-2023-arm64.pkr.hcl
assets/packer/build-agents/linux/install_common.al2023.sh
assets/packer/build-agents/linux/install_common.ubuntu.sh
assets/packer/build-agents/linux/install_octobuild.ubuntu.x86_64.sh
assets/packer/build-agents/windows/windows.pkr.hcl

**Issue number:** Closes #308 
This PR does two things:
1. It improves the stability of build agent packer scripts, mainly by setting dpkg timeout parameters that ensure that dpkg locks (e.g. those acquired by SSM automation) don't impede installation of packages (on Ubuntu) and using `dnf` instead of `yum` (on Amazon Linux 2023).
2. It removes configuration variables that weren't used.
3. It lowers the [WinRM connection timeout](https://developer.hashicorp.com/packer/docs/communicators/winrm#winrm_timeout) from 1 hour to 15 minutes, to give faster feedback in case firewalls are blocking WinRM connections.
Only change in user experience is that there should now be fewer packer build failures.
I checked, but documentation …

fix: improve stability of build agent packer scripts, remove variables that aren't needed

---

assets/packer/build-agents/windows/README.md
assets/packer/build-agents/windows/base_setup.ps1

This installs the following necessary requirements for (auto)mounting FSx volumes on Windows build agents:
* NFS-Client Windows feature
* Python, botocore, boto3 (required for FSx automounter script)
Before: users would have to manually install the required packages after building the AMI
After: users won't have to install required packages after building the AMI
<details>
No
</details>

enhancement: install requirements for (auto)mounting FSx volumes on Windows build agents

---

modules/jenkins/README.md
modules/jenkins/alb.tf
modules/perforce/helix-authentication-service/README.md
modules/perforce/helix-authentication-service/alb.tf
modules/perforce/helix-swarm/README.md
modules/perforce/helix-swarm/alb.tf
modules/unreal/horde/README.md
modules/unreal/horde/alb.tf

**Issue number:** NA
Suppresses Checkov CKV_AWS_378 rule on all ALB target groups using HTTP to perform TLS termination. 
Suppresses Checkov CKV_AWS_378 rule on all ALB target groups using HTTP to perform TLS termination. 
<details>
No
</details>

chore(checkov): Suppresses CKV_AWS_378 rule

---

modules/jenkins/examples/complete/vpc.tf
modules/perforce/examples/complete/vpc.tf
modules/unreal/horde/examples/complete/vpc.tf
samples/simple-build-pipeline/vpc.tf

This change ensures that the NAT Gateway routes for private route tables are declared in `aws_route` resources, instead of through the `aws_route_table` resource that creates the route table. The rationale for this is that the way it's done now does not allow users to add their own routes to these route tables outside of the `aws_route_table` resource's route declarations.
Users that are basing their infrastructure off of the samples and have their own routes defined for the private route tables will no longer see their additions getting removed by Terraform incorrectly.
I have tested the changes for the Horde sample.
No changes in documentation are necessary.
<details>
<summary>Is this a breaking …

chore: define nat gateway routes outside of aws_route_table resources in samples and modules

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_improvements.yml
.github/ISSUE_TEMPLATE/feature_request.yml

- Modifies the issue template files so that the "triage" label is added by default when the issue templates are used.
<details>
</details>

chore: adds triage label to our issue templates

---

modules/unreal/horde/sg.tf

This adds a security group rule to the Horde Agents security group that allows inbound access on ports 7000-7010 from the same security group. This enables usage of UnrealBuildAccelerator.
Prior to this change, when using UnrealBuildAccelerator, users would see only a single agent performing and completing actual work, visible as bars in UbaVisualizer that eventually turn green on that agent, whilst others remain grey. Tasks would eventually fail.
This changes fixes this, by allowing build agents to transfer files and context between each other, resulting in is builds being performed on multiple build agents successfully, and tasks not failing.
Documentation changes not necessary for this change. …

fix(horde): allow inbound access to horde agents on ports 7000-7010 from other horde agents

---

.github/workflows/jenkins-deployment.yml
modules/jenkins/examples/complete/main.tf
modules/jenkins/examples/complete/versions.tf
modules/jenkins/examples/complete/vpc.tf

Adds a Github Actions workflow to plan, deploy and destroy the jenkins complete example template. This workflow triggers on any changes to `modules/jenkins/*`. Some best practice features have been disabled as they cause the automated destruction of the solution to fail.
- Adds a Github Actions workflow that:
- Triggers on any PR that changes `modules/jenkins/*`
- Prepares environment for terraform
- Runs `terraform plan` and posts the output as a comment in the triggering PR
- After manual approval, deploys the solution into the `cloud-game-development+ci` AWS account
- After manual approval, destroys the solution in the `cloud-game-development+ci` AWS account
- Disables the following features in the `modules/jenkins/examples/complete` template to allow for automated …

feat(jenkins): Adds GHA deployment workflow

---

modules/unreal/horde/ecs.tf

In order to retain agents on ECS container restart the `JwtIssuer` must be set to a value that won't change. By default horde uses `Dns.GetHostName()` which changes on restart.

fix(horde): add JwtIssuer to ensure container retains agents on restart

---

modules/perforce/helix-authentication-service/README.md
modules/perforce/helix-authentication-service/outputs.tf
modules/perforce/helix-swarm/README.md
modules/perforce/helix-swarm/outputs.tf

N/A
Small fix to expose ECS service target groups as outputs for Helix Swarm and Helix Core.
- Added Helix Swarm target group output: `target_group_arn`
- Added Helix Authentication Service target group output: `target_group_arn`
Users looking to share an application load balancer across services can now leverage the output target groups to forward traffic to the underlying services.
<details>
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

fix: Added service target group ARNs as outputs for HAS and Swarm

---

modules/perforce/helix-authentication-service/main.tf

This fixes an issue where if an admin password and admin username secret ARN were provided, the admin _username_ ARN would be used for the ADMIN_PASSWD environment variable, instead of the admin _password_. This meant that the username would be used as password in Helix Authentication Service's admin interface.
Before: users would **not** be able to log in to Helix Authentication Service using the credentials they configured.
After: users would be able to log in to Helix Authentication Service using the credentials they configured.
<details>
No
</details>
By submitting this …

fix: use provided admin password secret for Helix Authentication Service ADMIN_PASSWD, instead of the username secret

---

docs/modules/unreal/horde/examples/complete.md
modules/perforce/examples/complete/main.tf
modules/unreal/horde/alb.tf
modules/unreal/horde/asg.tf

Closes #455 
fix: Minor adjustments to Horde module resource cleanup and documentation. Adding ALB target group attachment for Perforce complete example.
- Adding `force_destroy = true` to ALB access logs bucket and Horde agent playbook bucket.
- Updating Horde documentation to remove erroneous Perforce references.
- Adding ALB attachment for Perforce Complete example.
Simplified destruction process for Horde. Previously `terraform destroy` against Horde complete example would error out because access logs bucket and playbook bucket were not empty.
Attached Perforce web services ALB to correct target group for Perforce complete example.
If …

fix: Minor adjustments to Horde module resource cleanup and documentation

---

modules/unreal/horde/sg.tf

If you set `create_external_alb` to `false`, this currently blocks the creation of the following ingress rules:
- `unreal_horde_inbound_internal_alb_api`
- `unreal_horde_inbound_internal_alb_grpc`
Internal ingress rules would only be blocked when `create_internal_alb` was set to `false` and not `create_external_alb`.
<details>
Not necessarily a breaking change but it may introduce an unexpected exposure. To elaborate, if people had `create_external_alb` set to `false`, this change would introduce new security group ingress rules on …

fix: create_external_alb set to false shouldn't block internal SG ingress rule creation

---

modules/teamcity/README.md
modules/teamcity/examples/simple/dns.tf
modules/teamcity/examples/simple/local.tf
modules/teamcity/examples/simple/main.tf
modules/teamcity/examples/simple/versions.tf
modules/teamcity/examples/simple/vpc.tf
modules/teamcity/local.tf
modules/teamcity/main.tf
modules/teamcity/outputs.tf
modules/teamcity/variables.tf
modules/teamcity/versions.tf

**Feature request:**  TeamCity Server on ECS Fargate #12
TeamCity server creation with mounted EFS and Aurora Serverless V2 PostgreSQL configuration. Load balancing, access logging, and health checks configured. Allows configuration of database resources with connection strings as well as providing self managed Amazon EFS file system and access points.
> Initial module creation with VPC and docker image running TeamCity server with mounted EFS for data and logs. Aurora Serverless V2 running PostgreSQL engine backing the TeamCity server. Resource creation is configurable, and checkov requirements are addressed.
> Using this module, a user will be able to deploy TeamCity Server hosted on an Amazon ECS container managed by AWS Fargate. The TeamCity Server will have an attached Amazon EFS …

TeamCity Module

---

assets/packer/build-agents/windows/windows.pkr.hcl

Changing default instance type and setting `region` value to `null` in `windows.pkr.hcl`. Changed default instance type from `t3.small` to `m5.large`.
Fixes #523 
After running `packer install` with `windows.pkr.hcl` in assets/packer/build-agents/windows, the script would fail to install all packages due to a timeout issue. After changing the instance type in `windows.pkr.hcl`, the packer script no longer times out and executes successfully. Also set the default value for `region` to `null` in `windows.pkr.hcl` to ensure the script deploys resources in the default region for the user.
If your change doesn't seem to apply, please leave them …

fix: Windows Build Agent Packer fails to install packages

---

modules/teamcity/main.tf

**Issue number:** Closes #577 
Added the `force_destroy = var.debug` configuration to the access logs bucket
adding `force_destroy = var.debug` to resource `"aws_s3_bucket" "teamcity_alb_access_logs_bucket"`
`terraform destroy` will now be able to destroy the module even if the bucket is not empty for debug
<details>
<summary>Is this a breaking change?</summary> 
no
</details>

Fix: TeamCity module ALB access log bucket force delete on debug

---

assets/packer/perforce/helix-core/p4_configure.sh
modules/perforce/examples/fsxn/data.tf
modules/perforce/examples/fsxn/dns.tf
modules/perforce/examples/fsxn/local.tf
modules/perforce/examples/fsxn/main.tf
modules/perforce/examples/fsxn/outputs.tf
modules/perforce/examples/fsxn/variables.tf
modules/perforce/examples/fsxn/versions.tf
modules/perforce/examples/fsxn/vpc.tf
modules/perforce/helix-core/README.md
modules/perforce/helix-core/data.tf
modules/perforce/helix-core/fsxn.tf
modules/perforce/helix-core/iam.tf
modules/perforce/helix-core/main.tf
modules/perforce/helix-core/outputs.tf
modules/perforce/helix-core/variables.tf
modules/perforce/helix-core/versions.tf

Closes #428 
This PR adds functionality to the Perforce Server (Helix Core) module to leverage FSx for NetApp ONTAP as a backing store. It also provides modifications to the `p4_configure.sh` startup script to mount ISCSI volumes from FSxN, and includes a simple example for deploying Helix Core with an existing FSxN filesystem.
- Add ISCSI mounting support to `p4_configure.sh` startup script.
- Adds `fsxn` example which deploys a single-AZ FSxN filesystem and a Helix Core server leveraging that filesystem for storage.
- Adds NetApp resources to the Helix Core module. Leverages the NetApp Terraform provider and the Lambda Link functionality to create filesystem specific resources (LUN, iGroup)
> Please share what the user …

Perforce Server module support for FSxN Storage

---

.github/workflows/tf-test-on-comment-modules-perforce.yml
modules/perforce/tests/01_create_resources_complete.tftest.hcl
modules/perforce/tests/02_p4_server_fsxn.tftest.hcl
modules/perforce/tests/setup/ssm.tf

Closes #480 
This PR adds tests for the new Perforce module by leveraging `terraform test` functionality. As mentioned in #480, currently this is scoped to only perform simple unit testing (with `terraform plan`) until Terraform is updated to allow for more robust error handling and retry logic for `terraform test`, especially where state is concerned.
This PR adds a new workflow file and related Terraform test files that are specific to the new Perforce module, and will test all of the current example implementations of the Perforce module. The goal is that this will allow basic automated tests for the module as additional functionality is added to it. When new functionality is added, additional examples and tests …

chore: Add Terraform tests for new Perforce module

---

modules/unreal/horde/README.md
modules/unreal/horde/alb.tf

Adds listeners to the external and internal ALBs to permanently forward http traffic to https.
Before: browsing to `http://horde.whatever.tld` in some browsers will just sit and spin forever because ALB black-holes traffic by default.
After: browsing to the same url will quickly redirect to the HTTPS secured URL.
<details>
No, this is purely an additive change.
</details>

feat(horde): add HTTP redirect listeners to ALBs

---

modules/perforce/modules/p4-server/main.tf
modules/perforce/modules/p4-server/outputs.tf
modules/perforce/modules/p4-server/variables.tf

Closes #644 
This PR resolves small naming issues that occurred when consolidating the Perforce modules. The current functionality did not provide a bug as current terraform tests do not check for user supplied username/password. Instead it defaults to assume that a user will use the username/password created for the users via secrets manager.
Identical as before, just a minor naming fix.
* [ x] I have performed a self-review of this change
* [x ] Changes have been tested
* [x ] Changes are documented
<details>
No
</details>
By …

fix: Minor Perforce module copy/paste naming resolution

---

modules/unreal/horde/README.md
modules/unreal/horde/ecs.tf
modules/unreal/horde/iam.tf
modules/unreal/horde/local.tf
modules/unreal/horde/variables.tf

This change allows users to bring their own Horde Server images, most frequently built from custom engine builds with the Engine/Source/Programs/Horde/BuildHorde.xml BuildGraph, which allows building the image from source and pushing it to ECR or similar.
* Expose `image` as a variable to the outside world
* Make `github_credentials_secret_arn` optional, since it isn't needed for ECR images
* Make authentication variables optional, since images with custom config files won't need them.
No changes to the existing experience.
<details>
Nope, just a new feature!
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

feat(horde): allow users to bring their own horde-server images

---

modules/unreal/horde/elasticache.tf
modules/unreal/horde/examples/complete/main.tf
modules/unreal/horde/examples/complete/versions.tf
modules/unreal/horde/iam.tf
modules/unreal/horde/local.tf
modules/unreal/horde/sg.tf
modules/unreal/horde/variables.tf

closes #509
Implemented Valkey as a supported elasticache engine type when deploying Horde. It is now the default engine.
Valkey can be deployed as a replication group instead of as a Redis cluster. Generalized some variable names to be non-Redis exclusive. Added appropriate conditionals to IAM permissions
From the main.tf, user can change engine:
elasticache_engine                = "valkey"
to 
elasticache_engine                = "redis"
* [Yes] I have performed a self-review of this change
* [Yes] Changes have been tested
* [See Below] Changes are documented
Henry would like …

Feat: Valkey support for Elasticache Ltang/horde/valkey

---

.github/workflows/tf-test-on-comment-modules-perforce.yml

none, adhoc fix.
Fixed GitHub Actions workflow to properly handle PR branches from fork repositories by adding the `repository` parameter and `fetch-depth: 0` to the checkout action. This resolves the issue where the workflow was failing to fetch branches from forks with errors like "failed with exit code 1" when attempting to fetch from repositories like 'secretdimension:fix/p4'.
**Before:**
- PRs from the main repository worked correctly
- PRs from fork repositories failed with git fetch errors
- Users contributing from forks couldn't run Terraform tests via comment commands
**After:**
- PRs from both main repository and forks work correctly
- All users can trigger Terraform tests via comment commands regardless of PR source
- Workflow consistently fetches the correct …

fix: update perforce tf test to support branches on forks

---

modules/perforce/outputs.tf

Currently output `shared_application_load_balancer_arn` refers to the nlb, not the alb. This fixes that.
This allows users to disable nlb creation while continuing to use the alb.
<details>
Potentially, if anyone was relying on the incorrect output behavior.
</details>

fix(p4): Fix typo'ed output.shared_application_load_balancer_arn

---

modules/perforce/main.tf
modules/perforce/modules/p4-server/README.md
modules/perforce/modules/p4-server/main.tf
modules/perforce/modules/p4-server/variables.tf
modules/perforce/variables.tf

Perforce server licences are tied to the server's private IP address, so it can be desirable to let folks specify one.
> Adds an input option to allow users to specify their Perforce server private IP.
<details>
No!
</details>

feat(p4): allow users to specify a private ip

---

modules/perforce/examples/create-resources-complete/security.tf

N/A
Updated security group rule descriptions in the Perforce example configuration to use generic language instead of personal references. Changed four security group ingress rule descriptions from referencing "Kevon" to "my public IP" for better generalization and professional documentation standards.
**Before:**
- Security group rule descriptions contained personal references like "Allow HTTPS traffic from Kevon"
- Documentation appeared personalized to a specific developer
- Users might be confused by the personal reference in example code
**After:**
- Security group rule descriptions use generic language like "Allow HTTPS traffic from my public IP"
- Documentation is more professional and universally applicable
- Users can easily understand that the rules apply to …

chore: remove kevon from description :(

---

docs/index.md

Fixes button linking to getting started page at the bottom of index.md (homepage).
Changed link attached to getting started button at the bottom of the index.md (homepage) of docs.
Better experience navigating docs.
<details>
no
</details>

fix: fixes button/link to getting started page in homepage

---

modules/perforce/main.tf
modules/perforce/modules/p4-code-review/README.md
modules/perforce/modules/p4-code-review/main.tf
modules/perforce/modules/p4-code-review/variables.tf
modules/perforce/variables.tf

This allows setting `P4CHARSET` on p4-code-review, which is required for Unicode servers.
* p4-code-review: Allow passing P4CHARSET to p4-code-review
* p4: Default P4CHARSET to `auto` when using a Unicode server
Users will now be able to run P4 Code Review against Unicode P4 servers.
<details>
No.
</details>

feat(p4): add p4charset support to p4-code-review

---

modules/perforce/modules/p4-code-review/main.tf

When a new deployment/task/container of P4 CR gets deployed, the trigger token is regenerated. Without this setting, the P4 extension config retains the old token, and the integration breaks.
* Forces P4 CR to re-write it's extension config to P4D upon launch.
This allows users to skip manually updating the trigger token upon redeployment.
<details>
No.
</details>

fix(p4-code-review): set SWARM_FORCE_EXT to fix token rollover

---

modules/unreal/horde/ecs.tf

Prevents potential rate limiting issues with Docker Hub pulls
This changes the docdb-cert container image from bash on Docker Hub to bash on Public ECR Gallery, which prevents issues with rate limiting on pulls.
<details>
No
</details>

fix(unreal/horde): use bash image from public ECR instead of Docker Hub

---

modules/unreal/horde/README.md
modules/unreal/horde/asg.tf
modules/unreal/horde/config/agent/horde-agent.ansible.yml
modules/unreal/horde/variables.tf

Different versions of Unreal use different versions of the dotnet runtime (<5.6 uses 6.0, >=5.6 uses 8.0). This allows users to specify which version of the dotnet runtime to install based on their Horde version and/or any modifications they've made.
Pipes through a `agent_dotnet_runtime_version` input to the ansible playbook.
Users may install whichever version of dotnet they would like.
<details>
No.
</details>

feat(horde): parameterize dotnet version installed on agents

---

samples/unreal-cloud-ddc-single-region/README.md

Not a breaking change, just a small nit-pick in one of the samples' docs

Fix hyperlink in unreal cloud sample

---

modules/perforce/modules/p4-code-review/README.md
modules/perforce/modules/p4-code-review/main.tf

By default, fully_qualified_domain_name doesn't have a scheme associated with it, so P4CR assumes http:// and configures the p4 extension with that. This leads to validation failures, as the p4 hook doesn't accept the 301 redirect to https.
<details>
No?
</details>

fix(p4-code-review): SWARM_HOST should be an https url
